use_frameworks!

platform :ios, '11.0'

target 'DPGodChat_Example' do
#  pod 'DPGodChat', :path => '../'
  pod 'DPGodChat'    , '~> 0.1.5'
target 'DPGodChat_Tests' do
  inherit! :search_paths

  end
end
