use_frameworks!

platform :ios, '9.0'

target 'DPGodChat_Example' do
#  pod 'DPGodChat', :path => '../'
  pod 'DPGodChat'    , '~> 0.1.9'
  pod 'MBProgressHUD', '1.1.0'

target 'DPGodChat_Tests' do
  inherit! :search_paths

  end
end
