use_frameworks!

platform :ios, '9.0'

target 'DPGodChat_Example' do
  pod 'DPGodChat', :path => '../'

target 'DPGodChat_Tests' do
  inherit! :search_paths

target 'ShareScreen' do
  pod 'DPGodChat', :path => '../'
end
  end
end
